---
title: "Análise de Correspondências Múltipla"
author: "Caroline Hernandes Monteiro"
date: "23/07/2021"
output: pdf_document
---

```{r}
library(tidyverse)
library(plotly)
library(ggrepel)
library(sjPlot)
library(FactoMineR)
library(knitr)
library(kableExtra)
library(cabootcrs)
```


```{r}
load(file = "perfil_investidor_aplicacao.RData")

# Perfil x Aplicação
sjt.xtab(var.row = perfil_investidor_aplicacao$perfil, 
         var.col = perfil_investidor_aplicacao$aplicacao,
         show.exp = TRUE, 
         show.row.prc = TRUE, 
         show.col.prc = TRUE)

# Perfil x Estado Civil
sjt.xtab(var.row = perfil_investidor_aplicacao$perfil, 
         var.col = perfil_investidor_aplicacao$estado_civil,
         show.exp = TRUE, 
         show.row.prc = TRUE, 
         show.col.prc = TRUE)

# Aplicação x Estado Civil
sjt.xtab(var.row = perfil_investidor_aplicacao$aplicacao, 
         var.col = perfil_investidor_aplicacao$estado_civil,
         show.exp = TRUE, 
         show.row.prc = TRUE, 
         show.col.prc = TRUE)
```


```{r}
# Perfil x Aplicação
tab_perfil_aplicacao <- table(perfil_investidor_aplicacao$perfil,
                              perfil_investidor_aplicacao$aplicacao)
qui2_perfil_aplicacao <- chisq.test(tab_perfil_aplicacao)

# Perfil x Estado Civil
tab_perfil_estadocivil <- table(perfil_investidor_aplicacao$perfil,
                                perfil_investidor_aplicacao$estado_civil)
qui2_perfil_estadocivil <- chisq.test(tab_perfil_estadocivil)

# Aplicação x Estado Civil
tab_aplicacao_estadocivil <- table(perfil_investidor_aplicacao$aplicacao,
                                   perfil_investidor_aplicacao$estado_civil)
qui2_aplic_estad <- chisq.test(tab_aplicacao_estadocivil)
```


Estabelecendo a matriz binária:

```{r}
matriz_binaria <- getindicator(Xinput = perfil_investidor_aplicacao[, 2:4])
CA(matriz_binaria)
```


Estabelecendo a matriz de Burt:

```{r}
matriz_burt <- getBurt(Xinput = perfil_investidor_aplicacao[, 2:4])
CA(matriz_burt)
```


Rodando a ACM:

```{r}
ACM <- MCA(perfil_investidor_aplicacao[, 2:4], method = "Indicador")
ACM$var$coord # coordenadas de cada categoria
round(ACM$var$coord, 3) %>%
  kable() %>%
  kable_styling(bootstrap_options = "striped", 
                full_width = T, 
                font_size = 12)
ACM$eig # inércias principais
ACM$ind$coord # coordenadas de cada observação

categorias <- apply(perfil_investidor_aplicacao[,2:4], 
                    MARGIN =  2, 
                    FUN = function(x) nlevels(as.factor(x)))
It <- (sum(categorias) - length(categorias)) / length(categorias)
sum(ACM$eig[,1])
It_explicada <- ACM$eig[,1] / sum(ACM$eig[,1])

data.frame(Dimensão = paste("Dimensão", 1:length(It_explicada)),
           Inércia_Total = It_explicada) %>%
  ggplot(aes(x = Dimensão, 
             y = Inércia_Total, 
             label = paste0(round(Inércia_Total,3)*100,"%"))) +
  geom_bar(stat = "identity",
           color = "#440154FF", 
           fill = "#287C8EFF") +
  geom_label(vjust = 2) +
  labs(title = paste("Inércia Total Explicada de",
                     paste0(sum(It_explicada) * 100),"%")) +
   theme_bw()

dimensoes <- sum(categorias) - length(categorias) # número de dimensões
```


Mapa perceptual:

```{r}
categorias <- apply(perfil_investidor_aplicacao[,2:4], 
                    MARGIN =  2, 
                    FUN = function(x) nlevels(as.factor(x))) #número de categorias por variável
ACM_mp <- data.frame(ACM$var$coord, Variável = rep(names(categorias), categorias))

ACM_mp %>%
  rownames_to_column() %>%
  rename(Categoria = 1) %>%
  mutate(Categoria = gsub("perfil.","", Categoria),
         Categoria = gsub("aplicacao.","", Categoria),
         Categoria = gsub("estado_civil.","", Categoria)) %>%
  kable() %>%
  kable_styling(bootstrap_options = "striped", 
                full_width = T, 
                font_size = 12)

ACM_mp %>%
  rownames_to_column() %>%
  rename(Categoria = 1) %>%
  ggplot(aes(x = Dim.1, 
             y = Dim.2, 
             label = Categoria, 
             color = Variável, 
             shape = Variável)) +
  geom_point() +
  geom_label_repel() +
  geom_vline(aes(xintercept = 0), linetype = "dashed", color = "grey") +
  geom_hline(aes(yintercept = 0), linetype = "dashed", color = "grey") +
  labs(x = paste("Dimensão 1:", paste0(round(ACM$eig[1,2], 2), "%")),
       y = paste("Dimensão 2:", paste0(round(ACM$eig[2,2], 2), "%"))) +
  scale_color_viridis_d() +
  theme(panel.background = element_rect("white"),
        panel.border = element_rect("NA"),
        panel.grid = element_line("gray95"),
        legend.position = "none")


ACM_observacoes_df <- data.frame(ACM$ind$coord)
ACM_observacoes_df %>% 
  ggplot(aes(x = Dim.1, y = Dim.2, label = perfil_investidor_aplicacao$estudante)) +
  geom_point(shape = 17, color = "#E76F5AFF", size = 2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey50") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey50") +
  geom_text_repel(max.overlaps = 100, size = 3) +
  geom_density2d(color = "gray80") +
  geom_label_repel(data = ACM_mp, 
                   aes(x = Dim.1, y = Dim.2, 
                       label = rownames(ACM_mp), 
                       fill = Variável), 
                   color = "white") +
  labs(x = paste("Dimensão 1:", paste0(round(ACM$eig[,2][1], digits = 2), "%")),
       y = paste("Dimensão 2:", paste0(round(ACM$eig[,2][2], digits = 2), "%"))) +
  scale_fill_viridis_d() +
  theme(panel.background = element_rect("white"),
        panel.border = element_rect("NA"),
        panel.grid = element_line("gray95"),
        legend.position = "none")

ACM_3D <- plot_ly()
ACM_3D <- add_trace(p = ACM_3D,
                    x = ACM_mp[,1],
                    y = ACM_mp[,2],
                    z = ACM_mp[,3],
                    mode = "text",
                    text = rownames(ACM_mp),
                    textfont = list(color = "#440154FF"),
                    showlegend = FALSE)
ACM_3D <- layout(p = ACM_3D,
                 scene = list(xaxis = list(title = colnames(ACM_mp)[1]),
                              yaxis = list(title = colnames(ACM_mp)[2]),
                              zaxis = list(title = colnames(ACM_mp)[3]),
                              aspectmode = "data"))
```

