---
title: "Cluster não Hierárquico"
author: "Caroline Hernandes Monteiro"
date: "20/06/2021"
output: pdf_document
---

```{r}
library(tidyverse)
library(cluster)
library(dendextend)
library(factoextra)
library(fpc)
library(gridExtra)
library(readxl)
```


```{r}
mcdonalds <- read.table("dados/MCDONALDS.csv", sep = ";", dec = ",", header = T)
rownames(mcdonalds) <- mcdonalds[,1]
mcdonalds <- mcdonalds[,-1]
mcdonalds.padronizado <- scale(mcdonalds)

mcdonalds2k <- kmeans(mcdonalds.padronizado, centers = 2)
fviz_cluster(mcdonalds2k, data = mcdonalds.padronizado, main = "Cluster K2")


mcdonalds3k <- kmeans(mcdonalds.padronizado, centers = 3)
mcdonalds4k <- kmeans(mcdonalds.padronizado, centers = 4)
mcdonalds5k <- kmeans(mcdonalds.padronizado, centers = 5)

plotKmeans1 <- fviz_cluster(mcdonalds2k, geom = "point", data = mcdonalds.padronizado) + ggtitle("k = 2")
plotKmeans2 <- fviz_cluster(mcdonalds3k, geom = "point",  data = mcdonalds.padronizado) + ggtitle("k = 3")
plotKmeans3 <- fviz_cluster(mcdonalds4k, geom = "point",  data = mcdonalds.padronizado) + ggtitle("k = 4")
plotKmeans4 <- fviz_cluster(mcdonalds5k, geom = "point",  data = mcdonalds.padronizado) + ggtitle("k = 5")
grid.arrange(plotKmeans1, plotKmeans2, plotKmeans3, plotKmeans4, nrow = 2)

fviz_nbclust(mcdonalds.padronizado, kmeans, method = "wss")
```

Usando o método kmeans para 2, 3, 4 e 5 clusters e plotando elbow para verificar o número ideal de clusters, vemos que não existe ganho para mais que 4 clusters.