---
title: "Teste TransUnion"
author: "Caroline - 145687"
date: "13 de dezembro de 2019"
output: pdf_document
---

```{r setup, include=FALSE}

library(readxl)

base <- read_xlsx("base_teste_TU.xlsx")
summary(base)
sum(base$KGB)
base$media_renda_pres_hh <- ifelse(base$media_renda_pres_hh == "-9999","Na",base$media_renda_pres_hh)
base$media_renda_presumida <- ifelse(base$media_renda_presumida == "-9999","Na",base$media_renda_presumida)
base$cod_escolaridade <- ifelse(base$cod_escolaridade == "-9999","Na",base$cod_escolaridade)
base$idade_na_emissao <- ifelse(base$idade_na_emissao == "-9999","Na",base$idade_na_emissao)
base$qtd_decl_isento <- ifelse(base$qtd_decl_isento == "-9999","Na",base$qtd_decl_isento)
base$dist_fronteira_m <- ifelse(base$dist_fronteira_m == "-9999","Na",base$dist_fronteira_m)
base$veic_outros_percap_m_munic <- ifelse(base$veic_outros_percap_m_munic == "-9999","Na",base$veic_outros_percap_m_munic)
base$automoveis_percap_m_munic <- ifelse(base$automoveis_percap_m_munic == "-9999","Na",base$automoveis_percap_m_munic)
base$caminonete_percap_m_munic <- ifelse(base$caminonete_percap_m_munic == "-9999","Na",base$caminonete_percap_m_munic)
base$caminhao_percap_m_munic <- ifelse(base$caminhao_percap_m_munic == "-9999","Na",base$caminhao_percap_m_munic)
base$qtd_email <- ifelse(base$qtd_email == "-9999", "Na", base$qtd_email)
base$qtd_tel_fixo <- ifelse(base$qtd_tel_fixo == "-9999", "Na", base$qtd_tel_fixo)
base$percent_bolsa_familia <- ifelse(base$percent_bolsa_familia == "-9999", "Na", base$percent_bolsa_familia)
base$qtde_consulta_6_tele <- ifelse(base$qtde_consulta_6_tele == "-9999", "Na", base$qtde_consulta_6_tele)
base$ind_estab_emprego <- ifelse(base$ind_estab_emprego == "-9999", "Na", base$ind_estab_emprego)
base$cod_escolaridade <- as.factor(base$cod_escolaridade)
base$media_renda_pres_hh <- as.numeric(base$media_renda_pres_hh)
base$media_renda_presumida <- as.numeric(base$media_renda_presumida)
base$idade_na_emissao <- as.factor(base$idade_na_emissao)
base$qtd_decl_isento <- as.numeric(base$qtd_decl_isento)
base$qtd_decl_10 <- as.factor(base$qtd_decl_10)
base$dist_fronteira_m <- as.numeric(base$dist_fronteira_m)
base$ind_estab_emprego <- as.numeric(base$ind_estab_emprego)
base$veic_outros_percap_m_munic <- as.numeric(base$veic_outros_percap_m_munic)
base$caminonete_percap_m_munic <- as.numeric(base$caminonete_percap_m_munic)
base$caminhao_percap_m_munic <- as.numeric(base$caminhao_percap_m_munic)
base$automoveis_percap_m_munic <- as.numeric(base$automoveis_percap_m_munic)
base$qtd_email <- as.numeric(base$qtd_email)
base$qtd_tel_fixo <- as.numeric(base$qtd_tel_fixo)
base$qtde_consulta_6_tele <- as.numeric(base$qtde_consulta_6_tele)
base$KGB <- as.factor(base$KGB)
base$percent_bolsa_familia <- as.numeric(base$percent_bolsa_familia)
base$qtd_email <- as.numeric(base$qtd_email)
base$qtd_tel_fixo <- as.numeric(base$qtd_tel_fixo)

```

Classificando variáveis de acordo com seus quartis:

```{r}

base$renda_media <- NA
base$renda_media <- ifelse(base$media_renda_presumida <= 1806, 1, 2)
base$renda_media <- ifelse(base$media_renda_presumida >= 2644, 3, base$renda_media)
base$renda_media <- ifelse(base$media_renda_presumida >= 3071, 4, base$renda_media)
base$renda_media <- as.factor(base$renda_media)
base$dist_front <- NA
base$dist_front <- ifelse(base$dist_fronteira_m <= 560276, 1, 2)
base$dist_front <- ifelse(base$dist_fronteira_m <= 861470, 3, base$dist_front)
base$dist_front <- ifelse(base$dist_fronteira_m >= 1094586, 4, base$dist_front)
base$dist_front <- as.factor(base$dist_front)
base$outros_veic <- NA
base$outros_veic <- ifelse(base$veic_outros_percap_m_munic <= 14, 1, 2)
base$outros_veic <- ifelse(base$veic_outros_percap_m_munic >= 22.08, 3, base$outros_veic)
base$outros_veic <- ifelse(base$veic_outros_percap_m_munic <= 28, 4, base$outros_veic)
base$outros_veic <- as.factor(base$outros_veic)
base$caminhonete <- NA
base$caminhonete <- ifelse(base$caminonete_percap_m_munic <= 39, 1, 2)
base$caminhonete <- ifelse(base$caminonete_percap_m_munic <= 54.42, 3, base$caminhonete)
base$caminhonete <- ifelse(base$caminonete_percap_m_munic >= 74, 4, base$caminhonete)
base$caminhonete <- as.factor(base$caminhonete)
base$caminhao <- NA
base$caminhao <- ifelse(base$caminhao_percap_m_munic <= 8, 1, 2)
base$caminhao <- ifelse(base$caminhao_percap_m_munic <= 12.53, 3, base$caminhao)
base$caminhao <- ifelse(base$caminhao_percap_m_munic >= 16, 4, base$caminhao)
base$caminhao <- as.factor(base$caminhao)
base$automoveis <- NA
base$automoveis <- ifelse(base$automoveis_percap_m_munic <= 199, 1, 2)
base$automoveis <- ifelse(base$automoveis_percap_m_munic <= 307.9, 3, base$automoveis)
base$automoveis <- ifelse(base$automoveis_percap_m_munic >= 421, 4, base$automoveis)
base$automoveis <- as.factor(base$automoveis)
base$renda_household <- NA
base$renda_household <- ifelse(base$media_renda_pres_hh <= 447, 1, 2)
base$renda_household <- ifelse(base$media_renda_pres_hh > 544, 3, base$renda_household)
base$renda_household <- as.factor(base$renda_household)
base$bolsa_familia <- NA
base$bolsa_familia <- ifelse(base$percent_bolsa_familia <= 3, 1, 2)
base$bolsa_familia <- ifelse(base$percent_bolsa_familia > 5, 3, base$bolsa_familia)
base$bolsa_familia <- as.factor(base$bolsa_familia)
base$consulta <- NA
base$consulta <- ifelse(base$qtde_consulta_6_tele < 5, 1,2)
base$consulta <- as.factor(base$consulta)
base$estab_emprego <- NA
base$estab_emprego <- ifelse(base$ind_estab_emprego <= 0, 1, 2)
base$estab_emprego <- ifelse(base$ind_estab_emprego > 2, 3, base$estab_emprego)
base$estab_emprego <- as.factor(base$estab_emprego)
base$email <- NA
base$email <- ifelse(base$qtd_email <= 2, 1, 2)
base$email <- as.factor(base$email)
base$tel <- NA
base$tel <- ifelse(base$qtd_tel_fixo <= 2, 1, 2)
base$tel <- as.factor(base$tel)
base$isento <- NA
base$isento <- ifelse(base$qtd_decl_isento < 3, 1, 2)
base$isento <- as.factor(base$isento)

```

```{r}
library(dplyr)
library(ggplot2)
library(caret)

inadimplente <- base %>% filter( KGB == '0')
bom_pagador <- base %>% filter(KGB == '1')

t1 <- with(base, table(cod_escolaridade, qtd_decl_isento))
t1.inadimplente <- with(inadimplente, table(cod_escolaridade, qtd_decl_isento))
t1.bom_pagador <- with(bom_pagador, table(cod_escolaridade, qtd_decl_isento))

b = ggplot(inadimplente, aes(cod_escolaridade, fill = ind_estab_emprego)) +
  geom_histogram(stat="count") +
  ylab("Frequência")

c = ggplot(bom_pagador, aes(cod_escolaridade, fill = ind_estab_emprego)) +
  geom_histogram(stat="count") +
  ylab("Frequência")


fit <- glm(factor(base$KGB) ~ factor(base$isento) + factor(base$renda_media) + factor(base$estab_emprego) + factor(base$consulta) + factor(base$tel) + factor(base$bolsa_familia), family = binomial)
summary(fit)

##confusionMatrix(table(base, fit))

```

